link:
  forward: TIO_000020
  reverse: TIO_000021
  file: sample.tsv
update:
  frequency: Four Year
  method: wget https://hmdb.ca/system/downloads/current/hmdb_metabolites.zip && unzip hmdb_metabolites.zip && python hmdbid2inchikey.py  
